version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: scholar
      MYSQL_USER: scholar
      MYSQL_PASSWORD: scholarpw
      MYSQL_ROOT_PASSWORD: rootpw
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "7000:7000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: scholar
      DB_USER: scholar
      DB_PASSWORD: scholarpw
      DB_POOL_MAX: 2
