name: Keep Render Services Alive

# Run every 10 minutes to prevent free tier spin-down
on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:  # Allow manual trigger from GitHub Actions tab

jobs:
  ping-services:
    runs-on: ubuntu-latest
    
    steps:
      - name: Ping REST API Service
        run: |
          echo "🔄 Pinging REST API service..."
          API_URL="${{ secrets.REST_API_URL }}"
          
          if [ -n "$API_URL" ]; then
            response=$(curl -s -o /dev/null -w "%{http_code}" "$API_URL/actuator/health" || echo "000")
            
            if [ "$response" = "200" ]; then
              echo "✅ REST API is alive (HTTP $response)"
            else
              echo "⚠️ REST API returned HTTP $response"
            fi
          else
            echo "⚠️ REST_API_URL secret not configured - skipping"
          fi
        continue-on-error: true

      - name: Ping Vaadin UI Service
        run: |
          echo "🔄 Pinging Vaadin UI service..."
          UI_URL="${{ secrets.VAADIN_UI_URL }}"
          
          if [ -n "$UI_URL" ]; then
            response=$(curl -s -o /dev/null -w "%{http_code}" "$UI_URL/actuator/health" || echo "000")
            
            if [ "$response" = "200" ]; then
              echo "✅ Vaadin UI is alive (HTTP $response)"
            else
              echo "⚠️ Vaadin UI returned HTTP $response"
            fi
          else
            echo "⚠️ VAADIN_UI_URL secret not configured - skipping"
          fi
        continue-on-error: true

      - name: Summary
        run: |
          echo "📊 Keep-alive check completed at $(date)"
          echo "Next check in 10 minutes"
